name: Feature Request
description: Suggest a new feature or enhancement for CopyVersa v2
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: Alternative approaches could be...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Content Selection
        - Format Conversion
        - User Interface
        - Performance
        - Accessibility
        - Integration
        - Settings/Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        1. When I'm working on...
        2. I need to...
        3. This would help me...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If you have any mockups, screenshots, or examples, please share them
      placeholder: Drag and drop images here or paste them

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects or constraints to consider?
      placeholder: This might require...

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Requirements
      description: Where should this feature work?
      options:
        - label: All websites
        - label: Specific websites (please specify in additional context)
        - label: Desktop only
        - label: Should work with existing features

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, links, or information about the feature request
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: This feature aligns with CopyVersa's core purpose (content selection and copying)
          required: true
        - label: I have provided clear use cases and examples
          required: true
